# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payuser',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='promos',
            name='promoCode',
            field=models.CharField(max_length=20),
        ),
    ]
