# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161001_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
