# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161001_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
