# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161001_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='childs',
            field=models.ManyToManyField(blank=True, null=True, to='app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Expense'),
        ),
    ]
