# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161001_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_master', to='app.User'),
        ),
    ]
