# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161001_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='childs',
        ),
        migrations.AddField(
            model_name='user',
            name='childs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
