# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161001_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expenses',
        ),
    ]
