# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20161001_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(error_messages={'required': 'This field is required'}, max_length=30, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('allowance', models.IntegerField()),
                ('is_master', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_master', to='app.PayUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='master',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='merchant_id',
        ),
        migrations.AlterField(
            model_name='approval',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PayUser'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_master', to='app.PayUser'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PayUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='payuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
