# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161001_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=10, unique=True)),
                ('amount', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='approval',
            name='child',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='master',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='payuser',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='payuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='payuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payuser',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='payuser',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='payuser',
            name='master',
        ),
        migrations.AlterField(
            model_name='payuser',
            name='phone',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.AddField(
            model_name='promos',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PayUser'),
        ),
    ]
