# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161001_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promos',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
