# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161001_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='promoCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
